/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void panel1_Click1(GPanel source, GEvent event) { //_CODE_:panel1:967993:
  println("panel1 - GPanel >> GEvent." + event + " @ " + millis());
} //_CODE_:panel1:967993:

public void DiskSelectText_change(GTextField source, GEvent event) { //_CODE_:DiskSelectText:513186:
  println("DiskSelectText - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:DiskSelectText:513186:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  panel1 = new GPanel(this, 0, -20, 200, 70, "Tab bar text");
  panel1.setText("Tab bar text");
  panel1.setOpaque(true);
  panel1.addEventHandler(this, "panel1_Click1");
  DiskSelectLabel = new GLabel(this, 10, 30, 130, 20);
  DiskSelectLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  DiskSelectLabel.setText("Select Disk Amount");
  DiskSelectLabel.setTextBold();
  DiskSelectLabel.setOpaque(false);
  DiskSelectText = new GTextField(this, 150, 30, 40, 20, G4P.SCROLLBARS_NONE);
  DiskSelectText.setOpaque(true);
  DiskSelectText.addEventHandler(this, "DiskSelectText_change");
  panel1.addControl(DiskSelectLabel);
  panel1.addControl(DiskSelectText);
}

// Variable declarations 
// autogenerated do not edit
GPanel panel1; 
GLabel DiskSelectLabel; 
GTextField DiskSelectText; 
